name: Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_homeworks:
    name: Validate all homeworks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: ["01", "02", "03", "04", "05", "06", "07", "10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build C extension and Install the package (hw 10)
        run: |
          cd 10
          python setup.py build_ext --inplace
          pip install .

      - name: Check flake8
        run: flake8 .

      - name: Check pylint
        if: ${{ always() }}
        run: pylint ./*/*.py

      - name: Check tests with unittest for ${{ matrix.folder }}
        if: ${{ always() }}
        run: coverage run -m unittest discover -s ${{ matrix.folder }} -p "test_*.py" -t "."

      - name: Check test coverage
        run: coverage report -m
